package web.uitc.uitcbackend.entity.enums;

public enum Permission {
    ADD_USER, EDIT_USER, DELETE_USER, VIEW_USERS,
    ADD_TEACHER, EDIT_TEACHER, DELETE_TEACHER, VIEW_TEACHERS,
    ADD_COURSE, EDIT_COURSE, DELETE_COURSE, VIEW_COURSES,
    UPLOAD_ATTACHMENT, DOWNLOAD_ATTACHMENT, VIEW_ATTACHMENTS,
}